# Generated by Django 4.1.5 on 2023-01-17 16:32

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('aysaApp', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', mapbox_location_field.models.LocationField(map_attrs={})),
            ],
        ),
    ]
