# Generated by Django 4.1.5 on 2023-01-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aysaApp', '0003_localaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='localaddress',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localaddress',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
